// Code generated by protoc-gen-go. DO NOT EDIT.
// source: autoscale.proto

// import "google/protobuf/timestamp.proto";

package autoscale

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetTopologyRequest struct {
	TidbClusterID        string   `protobuf:"bytes,1,opt,name=tidbClusterID,proto3" json:"tidbClusterID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTopologyRequest) Reset()         { *m = GetTopologyRequest{} }
func (m *GetTopologyRequest) String() string { return proto.CompactTextString(m) }
func (*GetTopologyRequest) ProtoMessage()    {}
func (*GetTopologyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_dc6a430c3808dc1b, []int{0}
}

func (m *GetTopologyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTopologyRequest.Unmarshal(m, b)
}
func (m *GetTopologyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTopologyRequest.Marshal(b, m, deterministic)
}
func (m *GetTopologyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTopologyRequest.Merge(m, src)
}
func (m *GetTopologyRequest) XXX_Size() int {
	return xxx_messageInfo_GetTopologyRequest.Size(m)
}
func (m *GetTopologyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTopologyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetTopologyRequest proto.InternalMessageInfo

func (m *GetTopologyRequest) GetTidbClusterID() string {
	if m != nil {
		return m.TidbClusterID
	}
	return ""
}

type ResumeAndGetTopologyRequest struct {
	TidbClusterID        string   `protobuf:"bytes,1,opt,name=tidbClusterID,proto3" json:"tidbClusterID,omitempty"`
	TargetPodCnt         string   `protobuf:"bytes,2,opt,name=targetPodCnt,proto3" json:"targetPodCnt,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResumeAndGetTopologyRequest) Reset()         { *m = ResumeAndGetTopologyRequest{} }
func (m *ResumeAndGetTopologyRequest) String() string { return proto.CompactTextString(m) }
func (*ResumeAndGetTopologyRequest) ProtoMessage()    {}
func (*ResumeAndGetTopologyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_dc6a430c3808dc1b, []int{1}
}

func (m *ResumeAndGetTopologyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResumeAndGetTopologyRequest.Unmarshal(m, b)
}
func (m *ResumeAndGetTopologyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResumeAndGetTopologyRequest.Marshal(b, m, deterministic)
}
func (m *ResumeAndGetTopologyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResumeAndGetTopologyRequest.Merge(m, src)
}
func (m *ResumeAndGetTopologyRequest) XXX_Size() int {
	return xxx_messageInfo_ResumeAndGetTopologyRequest.Size(m)
}
func (m *ResumeAndGetTopologyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ResumeAndGetTopologyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ResumeAndGetTopologyRequest proto.InternalMessageInfo

func (m *ResumeAndGetTopologyRequest) GetTidbClusterID() string {
	if m != nil {
		return m.TidbClusterID
	}
	return ""
}

func (m *ResumeAndGetTopologyRequest) GetTargetPodCnt() string {
	if m != nil {
		return m.TargetPodCnt
	}
	return ""
}

type GetTopologyResponse struct {
	TidbClusterID        string   `protobuf:"bytes,1,opt,name=tidbClusterID,proto3" json:"tidbClusterID,omitempty"`
	Timestamp            int64    `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	TopologyList         []string `protobuf:"bytes,3,rep,name=topologyList,proto3" json:"topologyList,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTopologyResponse) Reset()         { *m = GetTopologyResponse{} }
func (m *GetTopologyResponse) String() string { return proto.CompactTextString(m) }
func (*GetTopologyResponse) ProtoMessage()    {}
func (*GetTopologyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_dc6a430c3808dc1b, []int{2}
}

func (m *GetTopologyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTopologyResponse.Unmarshal(m, b)
}
func (m *GetTopologyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTopologyResponse.Marshal(b, m, deterministic)
}
func (m *GetTopologyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTopologyResponse.Merge(m, src)
}
func (m *GetTopologyResponse) XXX_Size() int {
	return xxx_messageInfo_GetTopologyResponse.Size(m)
}
func (m *GetTopologyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTopologyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetTopologyResponse proto.InternalMessageInfo

func (m *GetTopologyResponse) GetTidbClusterID() string {
	if m != nil {
		return m.TidbClusterID
	}
	return ""
}

func (m *GetTopologyResponse) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *GetTopologyResponse) GetTopologyList() []string {
	if m != nil {
		return m.TopologyList
	}
	return nil
}

type ResumeAndGetTopologyResponse struct {
	HasErr               bool                 `protobuf:"varint,1,opt,name=hasErr,proto3" json:"hasErr,omitempty"`
	ErrInfo              string               `protobuf:"bytes,2,opt,name=errInfo,proto3" json:"errInfo,omitempty"`
	CurState             string               `protobuf:"bytes,3,opt,name=curState,proto3" json:"curState,omitempty"`
	Topology             *GetTopologyResponse `protobuf:"bytes,4,opt,name=topology,proto3" json:"topology,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ResumeAndGetTopologyResponse) Reset()         { *m = ResumeAndGetTopologyResponse{} }
func (m *ResumeAndGetTopologyResponse) String() string { return proto.CompactTextString(m) }
func (*ResumeAndGetTopologyResponse) ProtoMessage()    {}
func (*ResumeAndGetTopologyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_dc6a430c3808dc1b, []int{3}
}

func (m *ResumeAndGetTopologyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResumeAndGetTopologyResponse.Unmarshal(m, b)
}
func (m *ResumeAndGetTopologyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResumeAndGetTopologyResponse.Marshal(b, m, deterministic)
}
func (m *ResumeAndGetTopologyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResumeAndGetTopologyResponse.Merge(m, src)
}
func (m *ResumeAndGetTopologyResponse) XXX_Size() int {
	return xxx_messageInfo_ResumeAndGetTopologyResponse.Size(m)
}
func (m *ResumeAndGetTopologyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ResumeAndGetTopologyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ResumeAndGetTopologyResponse proto.InternalMessageInfo

func (m *ResumeAndGetTopologyResponse) GetHasErr() bool {
	if m != nil {
		return m.HasErr
	}
	return false
}

func (m *ResumeAndGetTopologyResponse) GetErrInfo() string {
	if m != nil {
		return m.ErrInfo
	}
	return ""
}

func (m *ResumeAndGetTopologyResponse) GetCurState() string {
	if m != nil {
		return m.CurState
	}
	return ""
}

func (m *ResumeAndGetTopologyResponse) GetTopology() *GetTopologyResponse {
	if m != nil {
		return m.Topology
	}
	return nil
}

func init() {
	proto.RegisterType((*GetTopologyRequest)(nil), "autoscale.GetTopologyRequest")
	proto.RegisterType((*ResumeAndGetTopologyRequest)(nil), "autoscale.ResumeAndGetTopologyRequest")
	proto.RegisterType((*GetTopologyResponse)(nil), "autoscale.GetTopologyResponse")
	proto.RegisterType((*ResumeAndGetTopologyResponse)(nil), "autoscale.ResumeAndGetTopologyResponse")
}

func init() { proto.RegisterFile("autoscale.proto", fileDescriptor_dc6a430c3808dc1b) }

var fileDescriptor_dc6a430c3808dc1b = []byte{
	// 343 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x92, 0x41, 0x4b, 0xe3, 0x50,
	0x10, 0xc7, 0x37, 0x9b, 0xa5, 0xdb, 0x4c, 0x77, 0x59, 0x78, 0x2b, 0x12, 0x6a, 0x95, 0x12, 0x44,
	0x7b, 0x4a, 0xa1, 0xc5, 0x4b, 0x6f, 0xb5, 0x8a, 0x14, 0x44, 0x24, 0xf5, 0xe4, 0xed, 0xb5, 0x1d,
	0x9f, 0x81, 0x24, 0x13, 0xdf, 0x9b, 0x80, 0x1e, 0xfc, 0x3e, 0x7e, 0x12, 0x3f, 0x97, 0xf8, 0x48,
	0xd3, 0x16, 0xaa, 0x15, 0x6f, 0x99, 0x7f, 0xfe, 0xf9, 0xff, 0x66, 0x32, 0x03, 0xff, 0x64, 0xc1,
	0x64, 0x66, 0x32, 0xc1, 0x30, 0xd7, 0xc4, 0x24, 0xbc, 0x4a, 0x08, 0x06, 0x20, 0x2e, 0x90, 0x6f,
	0x28, 0xa7, 0x84, 0xd4, 0x53, 0x84, 0x0f, 0x05, 0x1a, 0x16, 0x87, 0xf0, 0x97, 0xe3, 0xf9, 0x74,
	0x94, 0x14, 0x86, 0x51, 0x8f, 0xcf, 0x7c, 0xa7, 0xed, 0x74, 0xbc, 0x68, 0x5d, 0x0c, 0x14, 0xec,
	0x45, 0x68, 0x8a, 0x14, 0x87, 0xd9, 0xfc, 0xbb, 0x21, 0x22, 0x80, 0x3f, 0x2c, 0xb5, 0x42, 0xbe,
	0xa6, 0xf9, 0x28, 0x63, 0xff, 0xa7, 0x35, 0xad, 0x69, 0xc1, 0x33, 0xfc, 0x5f, 0xcb, 0x37, 0x39,
	0x65, 0x06, 0xbf, 0x08, 0x68, 0x81, 0xc7, 0x71, 0x8a, 0x86, 0x65, 0x9a, 0xdb, 0x74, 0x37, 0x5a,
	0x0a, 0x16, 0x5f, 0xe6, 0x5e, 0xc6, 0x86, 0x7d, 0xb7, 0xed, 0x5a, 0xfc, 0x8a, 0x16, 0xbc, 0x38,
	0xd0, 0xda, 0x3c, 0x68, 0xd9, 0xc8, 0x2e, 0xd4, 0xee, 0xa5, 0x39, 0xd7, 0xda, 0x76, 0x50, 0x8f,
	0xca, 0x4a, 0xf8, 0xf0, 0x1b, 0xb5, 0x1e, 0x67, 0x77, 0x54, 0x8e, 0xb5, 0x28, 0x45, 0x13, 0xea,
	0xb3, 0x42, 0x4f, 0x58, 0x32, 0xfa, 0xae, 0x7d, 0x55, 0xd5, 0x62, 0x00, 0xf5, 0x05, 0xde, 0xff,
	0xd5, 0x76, 0x3a, 0x8d, 0xde, 0x41, 0xb8, 0xdc, 0xe0, 0x06, 0x7e, 0x54, 0xf9, 0x7b, 0xaf, 0x0e,
	0x78, 0xc3, 0x82, 0x69, 0xf2, 0xee, 0x15, 0x57, 0xd0, 0x58, 0xb1, 0x8b, 0xfd, 0x8f, 0x62, 0xec,
	0xbe, 0x9a, 0x5b, 0x28, 0xc1, 0x0f, 0x11, 0xc3, 0xce, 0xa6, 0xff, 0x20, 0x8e, 0x56, 0xbe, 0xfc,
	0xe4, 0x22, 0x9a, 0xc7, 0x5b, 0x7d, 0x0b, 0xd4, 0xe9, 0xc9, 0x6d, 0x5f, 0x11, 0xa9, 0x04, 0x43,
	0x45, 0x89, 0xcc, 0x54, 0x48, 0x5a, 0x75, 0x95, 0xce, 0x67, 0x5d, 0x7c, 0x94, 0x69, 0x9e, 0xa0,
	0xe9, 0x56, 0x59, 0xcb, 0xa7, 0x69, 0xcd, 0x1e, 0x78, 0xff, 0x2d, 0x00, 0x00, 0xff, 0xff, 0x65,
	0x04, 0xc4, 0x6d, 0xf3, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AutoScaleClient is the client API for AutoScale service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AutoScaleClient interface {
	GetTopology(ctx context.Context, in *GetTopologyRequest, opts ...grpc.CallOption) (*GetTopologyResponse, error)
	ResumeAndGetTopology(ctx context.Context, in *ResumeAndGetTopologyRequest, opts ...grpc.CallOption) (*ResumeAndGetTopologyResponse, error)
}

type autoScaleClient struct {
	cc *grpc.ClientConn
}

func NewAutoScaleClient(cc *grpc.ClientConn) AutoScaleClient {
	return &autoScaleClient{cc}
}

func (c *autoScaleClient) GetTopology(ctx context.Context, in *GetTopologyRequest, opts ...grpc.CallOption) (*GetTopologyResponse, error) {
	out := new(GetTopologyResponse)
	err := c.cc.Invoke(ctx, "/autoscale.AutoScale/GetTopology", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *autoScaleClient) ResumeAndGetTopology(ctx context.Context, in *ResumeAndGetTopologyRequest, opts ...grpc.CallOption) (*ResumeAndGetTopologyResponse, error) {
	out := new(ResumeAndGetTopologyResponse)
	err := c.cc.Invoke(ctx, "/autoscale.AutoScale/ResumeAndGetTopology", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AutoScaleServer is the server API for AutoScale service.
type AutoScaleServer interface {
	GetTopology(context.Context, *GetTopologyRequest) (*GetTopologyResponse, error)
	ResumeAndGetTopology(context.Context, *ResumeAndGetTopologyRequest) (*ResumeAndGetTopologyResponse, error)
}

func RegisterAutoScaleServer(s *grpc.Server, srv AutoScaleServer) {
	s.RegisterService(&_AutoScale_serviceDesc, srv)
}

func _AutoScale_GetTopology_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTopologyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AutoScaleServer).GetTopology(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/autoscale.AutoScale/GetTopology",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AutoScaleServer).GetTopology(ctx, req.(*GetTopologyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AutoScale_ResumeAndGetTopology_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResumeAndGetTopologyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AutoScaleServer).ResumeAndGetTopology(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/autoscale.AutoScale/ResumeAndGetTopology",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AutoScaleServer).ResumeAndGetTopology(ctx, req.(*ResumeAndGetTopologyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AutoScale_serviceDesc = grpc.ServiceDesc{
	ServiceName: "autoscale.AutoScale",
	HandlerType: (*AutoScaleServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetTopology",
			Handler:    _AutoScale_GetTopology_Handler,
		},
		{
			MethodName: "ResumeAndGetTopology",
			Handler:    _AutoScale_ResumeAndGetTopology_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "autoscale.proto",
}
